import {
  LayoutDashboard,
  UsersRound,
  Network,
  Link,
  Settings,
  Server,
  Archive,
  ShieldCheck,
  Activity,
  Plus,
  Ellipsis,
  ChevronDown,
  ChevronRight,
  ArrowLeft,
  RefreshCw,
  LogOut,
  PanelLeft,
  X,
  Check,
  Search,
  Download,
  ArrowDownUp,
  Laptop,
  FileText,
  Pencil,
  Copy,
  TriangleAlert,
  Sun,
  Moon,
  Monitor,
  ArrowUpDown,
  SlidersHorizontal,
  CirclePlus,
  ChevronsLeft,
  ChevronsRight,
  ChevronLeft,
  LoaderCircle,
  ArrowDown,
  ArrowUp,
  ChevronsUpDown,
  type LucideProps,
} from "lucide-react";
const icons = {
  home: LayoutDashboard,
  users: UsersRound,
  routes: Network,
  link: Link,
  settings: Settings,
  server: Server,
  backup: Archive,
  shield: ShieldCheck,
  health: Activity,
  add: Plus,
  more: Ellipsis,
  chevron: ChevronDown,
  next: ChevronRight,
  back: ArrowLeft,
  refresh: RefreshCw,
  logout: LogOut,
  menu: PanelLeft,
  close: X,
  check: Check,
  search: Search,
  download: Download,
  traffic: ArrowDownUp,
  device: Laptop,
  document: FileText,
  edit: Pencil,
  copy: Copy,
  warning: TriangleAlert,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  sort: ArrowUpDown,
  view: SlidersHorizontal,
  filter: CirclePlus,
  first: ChevronsLeft,
  last: ChevronsRight,
  previous: ChevronLeft,
  loading: LoaderCircle,
  down: ArrowDown,
  up: ArrowUp,
  expand: ChevronsUpDown,
};
export type IconName = keyof typeof icons;
export function Icon({
  name,
  size = 16,
  ...props
}: LucideProps & { name: IconName }) {
  const Component = icons[name];
  return (
    <Component size={size} aria-hidden="true" strokeWidth={1.8} {...props} />
  );
}
